//Order
export const CREATE_ORDER = "CREATE_ORDER";
export const CHANGE_DEVICE_TYPE = "CHANGE_DEVICE_TYPE";
export const CHANGE_MANUFACTURER = "CHANGE_MANUFACTURER";
export const CHANGE_MANUFACTURER_FILTER = "CHANGE_MANUFACTURER_FILTER";
export const CHANGE_ORDER_STEP = "CHANGE_ORDER_STEP";
export const NEXT_ORDER_STEP = "NEXT_ORDER_STEP";
export const PREV_ORDER_STEP = "PREV_ORDER_STEP";
export const CHANGE_MODEL = "CHANGE_MODEL";
